### ISSUE TITLE
Interactive blog bost

### ISSUE THREAD

**Issue by viebel** [MrDallOca/spec-examples#1]
Nice initiative.

May I suggest you to write a series of blog post with your clojure.spec examples inside interactive code snippets.

It's super easy with [the Klipse plugin](https://github.com/viebel/klipse).

Here is an example of a blog post I wrote about `clojure.spec`: http://blog.klipse.tech/clojure/2016/05/30/spec.html

**Comment by tiagodalloca** [comment]
Cool!

But I really don't have any experience in writing blog posts. 

I don't even have a blog!

😆 

How should I start?

**Comment by viebel** [comment]
What's your email?

**Comment by tiagodalloca** [comment]
Well, this is a public thread.

I don't feel comfortable "exposing" my email this way.

Uderstand?

---

Edit:

English is not my mother tongue

**Comment by viebel** [comment]
Could you send me an email?
Check my github profile...

**Comment by tiagodalloca** [comment]
Blog posts on the way...

[Jekyll + Github Pages](https://mrdalloca.github.io/)

**Comment by tiagodalloca** [comment]
[First post](https://mrdalloca.github.io/clojure/2017/01/18/spec-example-1.html)
